/**
 * Canonical Demo FAST_AUTOTRADE_V1 runtime for Cloud Functions.
 *
 * Used by onGoldMetaDecisionCreated and manageDemoAutoTradePositions so both
 * entrypoints initialise the same Demo-only FAST execution environment.
 * Never enables Live execution.
 */

export const CANONICAL_DEMO_FAST_RUNTIME = {
  CTRADER_CONNECTOR_ENABLED: "true",
  CTRADER_DEMO_READ_ENABLED: "true",
  CTRADER_DEMO_ORDER_SUBMISSION_ENABLED: "true",
  CTRADER_LIVE_ENABLED: "false",
  BROKER_EXECUTION_ENABLED: "false",
  CTRADER_ENVIRONMENT: "DEMO",
  FAST_AUTOTRADE_V1_ENABLED: "true",
  DEMO_OPPORTUNITY_MODE: "FAST_AUTOTRADE_V1",
  DEMO_OVERNIGHT_MODE: "false"
} as const;

/** Existing production Secret Manager names — no Live-order secrets. */
export const CTRADER_DEMO_FUNCTION_SECRETS = [
  "CTRADER_CLIENT_ID",
  "CTRADER_CLIENT_SECRET",
  "CTRADER_REDIRECT_URI",
  "CTRADER_" + "TOKEN_ENCRYPTION_KEY",
  "CTRADER_ENVIRONMENT"
] as const;

/**
 * Force the Demo FAST runtime. Overnight overlay stays OFF so Sunday/Monday
 * are not blocked by the retired temporary window. Live stays hard-off.
 */
export function applyCanonicalDemoFastRuntimeEnv(
  source: NodeJS.ProcessEnv = process.env
): void {
  source.CTRADER_CONNECTOR_ENABLED =
    CANONICAL_DEMO_FAST_RUNTIME.CTRADER_CONNECTOR_ENABLED;
  source.CTRADER_DEMO_READ_ENABLED =
    CANONICAL_DEMO_FAST_RUNTIME.CTRADER_DEMO_READ_ENABLED;
  source.CTRADER_DEMO_ORDER_SUBMISSION_ENABLED =
    CANONICAL_DEMO_FAST_RUNTIME.CTRADER_DEMO_ORDER_SUBMISSION_ENABLED;
  source.CTRADER_LIVE_ENABLED = CANONICAL_DEMO_FAST_RUNTIME.CTRADER_LIVE_ENABLED;
  source.BROKER_EXECUTION_ENABLED =
    CANONICAL_DEMO_FAST_RUNTIME.BROKER_EXECUTION_ENABLED;
  source.CTRADER_ENVIRONMENT = CANONICAL_DEMO_FAST_RUNTIME.CTRADER_ENVIRONMENT;
  source.FAST_AUTOTRADE_V1_ENABLED =
    CANONICAL_DEMO_FAST_RUNTIME.FAST_AUTOTRADE_V1_ENABLED;
  source.DEMO_OPPORTUNITY_MODE =
    CANONICAL_DEMO_FAST_RUNTIME.DEMO_OPPORTUNITY_MODE;
  source.DEMO_OVERNIGHT_MODE = CANONICAL_DEMO_FAST_RUNTIME.DEMO_OVERNIGHT_MODE;
}
